# Generated by Django 3.0.4 on 2020-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='education',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
